version: "3.14"
services:
  app:
    image: openjdk:17
    volumes:
      - ./:/sources
      - ~/.m2/repository:/root/.m2/repository
    working_dir: /sources
    command: "./mvnw spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=${SUSPEND:-n},address=0.0.0.0:5005\""
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - GITHUB_APP_CERT
      - GITHUB_APP_CERT_FILE
      - GITHUB_ID
      - SLACK_API_TOKEN
      - JOBS_GITHUB_INSTALLATION_SCAN_INTERVAL
      - STATE_STORAGE_TYPE
      - STATE_STORAGE_FS_FILEPATH
      - STATE_STORAGE_GCS_BUCKET_NAME
      - STATE_STORAGE_GCS_BUCKET_SECRET
      - STATE_STORAGE_GCS_BUCKET_FILEPATH
      - GITHUB_API_ENDPOINT
