version: "3.14"
services:
  app:
    image: openjdk:11
    volumes:
      - ./:/sources
    working_dir: /sources
    command: "./mvnw spring-boot:run"
    environment:
      - GITHUB_APP_CERT
      - GITHUB_ID
      - SLACK_API_TOKEN
      - JOBS_GITHUB_INSTALLATION_SCAN_INTERVAL